"""driver application pdf status and submitted_at

Revision ID: d2078ad7da79
Revises: 39946ea92c56
Create Date: 2026-06-08 03:01:43.774512

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
import crypto


# revision identifiers, used by Alembic.
revision: str = 'd2078ad7da79'
down_revision: Union[str, Sequence[str], None] = '39946ea92c56'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('driverapplication', sa.Column('pdf_status', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('driverapplication', sa.Column('pdf_error', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('driverapplication', sa.Column('submitted_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('driverapplication', 'submitted_at')
    op.drop_column('driverapplication', 'pdf_error')
    op.drop_column('driverapplication', 'pdf_status')
    # ### end Alembic commands ###
